name: "multi event pipeline/Workflow"
on:
    push:
        branches:
            - master
            - test

    pull_request:
        branches:
            - master
        types:
            - closed
            - opened

    schedule:
            - cron: "0 10 * * 2,4"
        


jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "running on master/test push"
              run: echo "running on master push"

    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request"
              run: echo "running pull request"

    on-pull-request-opened:
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request opened"
              run: echo "Running on pull request opened"
            
    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"

    on-workflow-dispatch:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "running on workflow dispatch"
              run: echo "running on workflow dispatch!!"
 
    on-schedule: # Job 4
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on schedule" # Step 1
              run: echo "Running on schedule"